---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mcp-task-server-secrets
  namespace: mcp-dev
spec:
  encryptedData:
    MCP_API_KEY: AgCemVLpyX72qWVT8lc65+O+7oDBz+AP21AkeIpQmiHo5Gn9dGa8DX7gluyUjby9kJIZDmWFwA5Od3C0Ogk/SpcboS5fYkL4cEa9neJwCjBEDRGHE1kTNbo0wlKovQjdOhL4VXOdIBB7u9Tlyffnl0x5kP7W50lrny1S/12CBHT724vGhnP/oRt3yOdFhQ0GlH95M7+7LW1BNd8HJ3+pfDZiH8tqbhzPL/eaDgAULYZTWh2Tjpv7VWHcq+ETK0vUzt+X74GQtMyZKS7uKWdC99BMIEaIsv1dA1I2XexK0hAF+MOOtSvB7/EyO/1AHWDFzWeu+Lcgs7WHmIc6yLEGyHL7AOaiiy0vsSINInbuZ8eQPj7t2bhLWPdDAyh3fP6+dVQPHhMBn2yZP3q2Go4H4hILy4A1IL/CdSnkdYeJqXq8oorFHdyzcKnIhNp1CdeTg3zQuaJzxeCTIAcn4Ow9rSL+LR0y5iG2mY9P3pZf1zsmL5sFyllma1JAv61Q3hxgujAGEAryzgs8wUbtPzvgqKsYD3yISLQ5VXo0y69+cb/Zee1HalZklJeYTPFFWfOLotmxEnM/N34hLyiuTVw/MOBWJ5jzMQ7x/d/IjtyWSbtwEppaL2HJHs/o456Ubwt5Kw7+595Wy2d1DdNzZW4fybiAjPnjlXu1HVdL4ojEUmIg5/71n2kl+Roh2lW6IbazOS6ctKujSM6f7Hg=
    POSTGRES_PASSWORD: AgAuxKKRphGY0gEBr8Zm6QqNTb5aPCCfMr0pMobt9z7j1IzqYEUowLNV5BA1932Kh9IID7cT510Gil5dK0JwtIBIdwRlXCeTQPAFHdIeYq7GdLt9NSm1ZZ8ThybNpx/MvNVvst2ImNL5jwX0bkIuKR1AWqUeGsXqvS1IvPDAPVMOo6kdaR560qa1sGIal+xe0ITa/DyNwHn4qLdfYN/kCXhdR8IA2SXjPmbby6lw+FkEylhx09q8VKSxK+mXBCZwCEnSoIgXf6c7KH88ifpkhbbhzfWoagw44Xb3amn81jS3elrcUwjrgoOL8zwtSCKTX6aNnMr6JaflQy8mjuZsQ1Ff+3MbY2365Lp0GYVGZom9O1WNv5Q0N+gF500YrUJhjdxgCakAn7upJiscjtJuoMn7YcsmZiTpRwebugLgY/+/wfg/GvQPgXectA/0JMtMKeZd3zr67ZAHf9reBAfY8zH5bmD36VRZGTlaGMpzK1WH7BTB0bIX0TrAXAgIA3EKo+Za+QhGZ282Xnyf+J7dnVI6qZI9DYLFi15c0Y/86MYiqVWnre21Ve8bgiryTPvBoTZ83Mtf/e+GCnpzoAWzJEh3QPHVGlvj/87Yc7XVbYZZXuVUQ6mvD4KovOzAMDIrx0M3YnoNWvHhdGwkgoCMOmz4JdPU8bSZK0CFO5QvjQRSUn8YHs/dcgm9NLQVvl29KtRK8dH3vA==
  template:
    metadata:
      name: mcp-task-server-secrets
      namespace: mcp-dev
    type: Opaque
