apiVersion: v1
kind: Secret
metadata:
  name: mcp-task-server-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://gitlab.com/turisap/k8s-mcp.git
  username: oauth2
  password: glpat-1dAKM-DYF2fEg0_mqRWhxWM6MQpvOjEKdTo1ZnQ1eQ8.01.17078wxjq