replicaCount: 3

image:
  repository: mcp
  tag: latest
  pullPolicy: Never

service:
  port: 8080

resources:
  requests:
    cpu: "50m"
    memory: "64Mi"
  limits:
    cpu: "200m"
    memory: "128Mi"

config:
  addr: ":8080"

quota:
  requests:
     cpu: "500m"
     memory: "512Mi"
  limits:
     cpu: "2"
     memory: "16Gi"